In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Import the dataset
dataset = pd.read_csv('ny_hmda_2015.csv')
#X = dataset.iloc[:, [5, 7, 8, 9, 18, 20, 22, 23, 25, 35, 47, 49, 51, 53, 55, 57, 59, 61, 63, 66, 70, 71, 72, 73, 74, 75, 76, 77 ]].values
X = dataset.iloc[:, [5,8,18,20,23,25,35,47,49,51,53,57,59,61,63,7, 9, 22,55,66,70,71,72,73,74,75,76,77]].values
Y = dataset.iloc[:, 0].values

#Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values="NaN", strategy="mean", axis=0)
imputer = imputer.fit(X[:,0:28])
X[:,0:28] = imputer.transform(X[:,0:28])

/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (15,16,17,31,32,33,34,42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
X 

array([[2.00000000e+00, 5.00000000e+00, 2.00000000e+00, ...,
        5.87000000e+03, 2.52598970e+00, 1.09459999e+02],
       [2.00000000e+00, 5.00000000e+00, 1.00000000e+00, ...,
        3.51200000e+03, 2.52598970e+00, 1.60600006e+02],
       [2.00000000e+00, 3.00000000e+00, 1.00000000e+00, ...,
        8.35700000e+03, 2.52598970e+00, 1.34820007e+02],
       ...,
       [4.00000000e+00, 7.00000000e+00, 4.00000000e+00, ...,
        5.09300000e+03, 2.52598970e+00, 1.29479996e+02],
       [4.00000000e+00, 7.00000000e+00, 4.00000000e+00, ...,
        4.99700000e+03, 2.52598970e+00, 1.71649994e+02],
       [4.00000000e+00, 7.00000000e+00, 4.00000000e+00, ...,
        4.09200000e+03, 2.52598970e+00, 4.12500000e+01]])

In [4]:
# 5 8 18 20 23 25 35 47 49 51 53 57 59 61 63 

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
for i in range (0, 15):
    onehotencoder = OneHotEncoder(categorical_features = [i])
    X = onehotencoder.fit_transform(X).toarray()

    

/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_en

/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_en

In [6]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.87000000e+03, 2.52598970e+00, 1.09459999e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.51200000e+03, 2.52598970e+00, 1.60600006e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        8.35700000e+03, 2.52598970e+00, 1.34820007e+02],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.09300000e+03, 2.52598970e+00, 1.29479996e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.99700000e+03, 2.52598970e+00, 1.71649994e+02],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        4.09200000e+03, 2.52598970e+00, 4.12500000e+01]])

In [7]:
#Splitting the data set into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [8]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [9]:
#Fitting Random Forest Classifier to the train set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000)
classifier.fit(X_train, Y_train )


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [14]:
#Predicting the test results using the model
Y_pred = classifier.predict(X_test)
Y_pred_train = classifier.predict(X_train)

In [15]:
#Making the confusion matrix
# from sklearn.metrics import confusion_matrix
# ce = confusion_matrix(Y_test, Y_pred)
Y_pred

array([4, 1, 1, ..., 1, 1, 6])

In [23]:
from sklearn import metrics
# testing score
score = metrics.f1_score(Y_test, Y_pred, pos_label=list(set(Y_test)), average="macro")
# training score
score_train = metrics.f1_score(Y_train, Y_pred_train, pos_label=list(set(Y_train)),average="macro")

/Users/janmajayamall/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1052: UserWarning: Note that pos_label (set to [1, 2, 3, 4, 5, 6, 7]) is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


In [24]:
score


0.4139385922492816

In [25]:
score_train

1.0